server:
  port: 5000
spring:
  application:
    name: YGateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: abc
          uri: http://www.yanghuisen.cn
          predicates:
            - Path=/tags/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/gateway?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8
  redis:
    # Redis地址
    host: localhost
    # Redis端口
    port: 6379
    # RedisDB库
    database: 0
    # 链接超市
    timeout: 10000ms
    lettuce:
      pool:
        # 最大连接数
        max-active: 1024
        # 最大阻塞等待时间
        max-wait: 10000ms
        # 最大空闲时间
        max-idle: 200
        # 最小空闲链接
        min-idle: 5